application:
  title: authentication-client-oauth
  version: 1.0.0
  autor: 'Mitocode'

server:
  port: ${AUTH_CLIENT_PORT:8089}

spring:
  data:
    mongodb:
      database: mitocodedb
      uri: mongodb://localhost:27017/mitocodedb
