apiVersion: v1
kind: Namespace
metadata:
  name: mitocode
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: mitocode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: mitocodeacr9986.azurecr.io/discovery-server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8761
          env:
            - name: DISCOVERY_SERVER_PORT
              value: "8761"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: mitocode
spec:
  selector:
    app: discovery-server
  ports:
    - name: http
      port: 8761
      targetPort: http
  type: ClusterIP
