apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME-public
  namespace: mitocode
  labels:
    app: SERVICE_NAME
    exposure: public
spec:
  type: LoadBalancer
  selector:
    app: SERVICE_NAME
  ports:
    - name: http
      port: 80
      targetPort: CONTAINER_PORT
