server:
  port: ${PRODUCT_SERVER_PORT:9001}

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.mitocode.microservices.product_service.messaging.StockCommand
  data:
    mongodb:
      database: mitocodedb
      uri: mongodb://mitocode:mitocode@localhost:27018/mitocodedb?authSource=admin

encrypt:
  key: mitocode

info:
  app:
    name: Product Service Microservice
    description: Módulo de la arquitectura que disponibiliza información de los productos
    version: 1.0

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator

  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
    enable: true
swagger-ui:
  path: swagger-ui.html
  enable: true
