application:
  title: authentication-server-oauth2
  version: 1.0.0
  autor: 'Mitocode'

server:
  port: ${AUTH_SERVER_PORT:8088}

spring:
  data:
    mongodb:
      database: mitocodedb
      uri: mongodb://localhost:27018/mitocodedb
