
application:
  title: product-service
  version: 1.0.0
  autor: 'Mitocode'

server:
  port: ${PRODUCT_SERVER_PORT:9001}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.mitocode.microservices.product_service.messaging.StockCommand
  data:
    mongodb:
      database: mitocodedb
      uri: mongodb://mitocode:mitocode@localhost:27018/mitocodedb?authSource=admin

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
