
application:
  title: product-service
  version: 1.0.0
  autor: 'Mitocode'

spring:
  data:
    mongodb:
      database: mitocodedb
      uri: mongodb://mitocode:mitocode@localhost:27018/mitocodedb?authSource=admin

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
