scrape_configs:

  - job_name: "Product Service Mitocode"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 1s
    static_configs:
      - targets: ["product-service:9001"]
        labels:
          application: "Product Service"

  - job_name: "Audit Service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["audit-service:9004"]

  - job_name: "Product Query Service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["product-query-service:9005"]

  - job_name: "Order Saga Service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["order-saga-service:9006"]
