server:
  port: ${RIBBON_SERVER_PORT:9021}

application:
  title: client-service-ribbon
  version: 1.0.0
  autor: 'Mitocode'

spring:
  devtools:
    restart:
      enabled: false
  application:
    name: client-service-ribbon
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

user-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9004,localhost:9044
    ServerListRefreshInterval: 1500

product-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9001
    ServerListRefreshInterval: 1500
